/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.Atendimento;
import entidade.Midia;
import entidade.Titulo;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import negocio.NCliente;
import negocio.NDependente;
import negocio.NFuncionario;
import negocio.NMidia;
import negocio.NMulta;
import negocio.NTitulo;
import persistencia.AtendimentoDAO;
import persistencia.FuncionarioDAO;
import persistencia.MidiaDAO;
import persistencia.MultaDAO;
import persistencia.TituloDAO;

/**
 *
 * @author rafael
 */
public class CadDevolucao extends javax.swing.JInternalFrame {

    JDesktopPane painelPrincipal;

    /**
     * Creates new form CadReserva
     */
    public CadDevolucao() throws ParseException {
        initComponents();

        LocalDate dataManipulacao = LocalDate.now();
        DateTimeFormatter formatadorBarra = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtDataSaida.setText(dataManipulacao.format(formatadorBarra));
        txtStatus.setText("Ativo");
        
        DefaultComboBoxModel defaultComboBox;
        MultaDAO persistencia = new MultaDAO();

        try {
            defaultComboBox = new DefaultComboBoxModel(persistencia.comboBox().toArray());
            defaultComboBox.setSelectedItem("< Multa >");
            comboBoxMulta.setModel(defaultComboBox);
        } catch (SQLException ex) {
            Logger.getLogger(CadDependente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public CadDevolucao(JDesktopPane parametro) throws ParseException {
        this();
        painelPrincipal = parametro;
    }

    public CadDevolucao(JDesktopPane parametro, Atendimento atendimento) throws ParseException, Exception {
        this();
        painelPrincipal = parametro;
        carregarTela(atendimento);
    }

    public CadDevolucao(JDesktopPane parametro, Titulo titulo) throws ParseException {
        this();
        painelPrincipal = parametro;
        carregarTelaTitulo(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtAtendente = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtMidia = new javax.swing.JTextField();
        txtDataEntrada = new javax.swing.JTextField();
        txtDataSaida = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtDuracao = new javax.swing.JTextField();
        txtDesconto = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JLabel();
        radioCliente = new javax.swing.JRadioButton();
        radioDependente = new javax.swing.JRadioButton();
        comboBoxMulta = new javax.swing.JComboBox<>();

        setTitle("Devolução");

        jLabel1.setText("ID");

        jLabel2.setText("Título");

        jLabel3.setText("Data Entrada");

        jLabel4.setText("Tipo da Mídia");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnPesquisa.setText("Pesquisa");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");

        btnLimpar.setText("Limpar");

        btnFechar.setText("Fechar");

        jLabel5.setText("Quantidade");

        jLabel6.setText("Nome");

        jLabel8.setText("Status");

        jLabel9.setText("Duração");

        jLabel10.setText("Valor Total:");

        jLabel7.setText("Data Saída");

        jLabel11.setText("Atendente");

        jLabel12.setText("Desconto");

        jLabel13.setText("Multa");

        txtValorTotal.setText("R$00.00");

        radioCliente.setText("Cliente");

        radioDependente.setText("Dependente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMidia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAtendente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtDesconto, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDataEntrada, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDuracao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel10))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDataSaida)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtValorTotal)
                                                .addGap(0, 79, Short.MAX_VALUE))
                                            .addComponent(comboBoxMulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioCliente)
                                .addGap(18, 18, 18)
                                .addComponent(radioDependente))
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCliente)
                    .addComponent(radioDependente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMidia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(comboBoxMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtValorTotal))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnFechar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:

        try {

            PesquisaTituloLocacao janela = new PesquisaTituloLocacao(painelPrincipal);
            painelPrincipal.add(janela);
            janela.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:

        try {

            ListaDevolucao janela = new ListaDevolucao(painelPrincipal);
            painelPrincipal.add(janela);
            janela.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:

        try {

            Atendimento atendimento = new Atendimento();

            //tratativa do ID
            if (!txtId.getText().equals("")) {
                atendimento.setId(Integer.parseInt(txtId.getText()));
            }

            //Se for atendimento para cliente, setar ID do cliente.
            if (radioCliente.isSelected()) {
                atendimento.setCliente_id(Integer.parseInt(txtId.getText()));
            }

            //Se for atendimento para dependente, setar ID do dependente.
            if (radioDependente.isSelected()) {
                atendimento.setDependente_id(Integer.parseInt(txtId.getText()));
            }

            atendimento.setFuncionario_id(new FuncionarioDAO().pegaId(txtAtendente.getText()));
            atendimento.setTitulo_id(new TituloDAO().pegaId(txtTitulo.getText()));
            atendimento.setQuantidadeMidias(Integer.parseInt(txtQuantidade.getText()));

            String data1 = txtDataSaida.getText();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataSaida = formato.parse(data1);
            atendimento.setDataSaida(dataSaida);

            atendimento.setStatus(false);

            atendimento.setDuracao(Integer.parseInt(txtDuracao.getText()));

            //Manipulação da mídiaS
            Midia midia = new MidiaDAO().consultarPeloTitulo(new TituloDAO().pegaId(txtTitulo.getText()), txtMidia.getText());
            midia.setId(midia.getId());
            midia.setQuantidade((midia.getQuantidade() + Integer.parseInt(txtQuantidade.getText())));
            new MidiaDAO().alterar(midia);
            atendimento.setMidia_id(midia.getId());

            //Tratamento da Data
            String data2 = txtDataEntrada.getText();
            formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataEntrada = formato.parse(data2);
            atendimento.setDataEntrada(dataEntrada);

            long diffInMillies = Math.abs(dataEntrada.getTime() - dataSaida.getTime());
            long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
            
            Integer id_multa = new MultaDAO().pegaId(comboBoxMulta.getSelectedItem().toString());
            
            atendimento.setMulta_id(id_multa);
            
            Double valor, valorMulta;
            MultaDAO perMulta = new MultaDAO();
            
            switch(comboBoxMulta.getSelectedIndex()){
                case 1:
                    valorMulta = perMulta.consultar(id_multa).getValor();
                    valor = atendimento.getValorTotal() + (diff * valorMulta);
                    atendimento.setValorTotal(valor);
                    txtValorTotal.setText(valor.toString());
                    break;
                case 2:
                    valorMulta = perMulta.consultar(id_multa).getValor();
                    valor = Double.parseDouble(txtValorTotal.getText()) + valorMulta;
                    atendimento.setValorTotal(valor);
                    txtValorTotal.setText(valor.toString());
                    break;
                case 3:
                    valorMulta = perMulta.consultar(id_multa).getValor();
                    valor = Double.parseDouble(txtValorTotal.getText()) + valorMulta;
                    atendimento.setValorTotal(valor);
                    txtValorTotal.setText(valor.toString());
                    break;
                case 4:
                    valorMulta = perMulta.consultar(id_multa).getValor();
                    valor = Double.parseDouble(txtValorTotal.getText()) + valorMulta;
                    atendimento.setValorTotal(valor);
                    txtValorTotal.setText(valor.toString());
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Opção inválida");
            }


            if (radioCliente.isSelected()) {
                new AtendimentoDAO().alterarLocacaoCliente(atendimento);
            } else {
                new AtendimentoDAO().alterarLocacaoDependente(atendimento);
            }

            JOptionPane.showMessageDialog(this, "Operação efetuada com sucesso!");

            //limpar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro" + e.getMessage());
        }

    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboBoxMulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioCliente;
    private javax.swing.JRadioButton radioDependente;
    private javax.swing.JTextField txtAtendente;
    private javax.swing.JTextField txtDataEntrada;
    private javax.swing.JTextField txtDataSaida;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMidia;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JLabel txtValorTotal;
    // End of variables declaration//GEN-END:variables

    private void carregarTelaTitulo(Titulo titulo) throws ParseException {

        txtTitulo.setText(titulo.getNome());

        btnExcluir.setEnabled(true);

    }

    private void carregarTela(Atendimento atendimento) throws ParseException, Exception {

        txtId.setText(atendimento.getId() + "");

        if (atendimento.getCliente_id() != 0) {
            txtNome.setText(new NCliente().consultar(atendimento.getCliente_id()).getNome());
        }

        if (atendimento.getDependente_id() != 0) {
            txtNome.setText(new NDependente().consultar(atendimento.getDependente_id()).getNome());
        }

        txtAtendente.setText(new NFuncionario().consultar(atendimento.getFuncionario_id()).getNome());
        txtTitulo.setText(new NTitulo().consultar(atendimento.getTitulo_id()).getNome());
        txtQuantidade.setText(atendimento.getQuantidadeMidias() + "");
        txtMidia.setText(new NMidia().consultar(atendimento.getMidia_id()).getTipoMidia());

        Midia midia = new MidiaDAO().consultarPeloTitulo(new TituloDAO().pegaId(new NTitulo().consultar(atendimento.getTitulo_id()).getNome()), new NMidia().consultar(atendimento.getMidia_id()).getTipoMidia());

        if (atendimento.isStatus() == true) {
            txtStatus.setText("ATIVO");
        } else {
            txtStatus.setText("INATIVO");
        }

        txtDuracao.setText(atendimento.getDuracao() + "");

        SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
        String result = out.format(in.parse(atendimento.getDataEntrada().toString()));

        txtDataEntrada.setText(result);

        txtValorTotal.setText(atendimento.getValorTotal() + "");

        btnExcluir.setEnabled(true);

    }

}
