/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.Midia;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NMidia;
import negocio.NTitulo;

/**
 *
 * @author rafael
 */
public class ListaMidia extends javax.swing.JInternalFrame {

    JDesktopPane painelPrincipal;

    /**
     * Creates new form ListaMidia
     */
    public ListaMidia() {
        initComponents();
        carregarTabela();
    }

    public ListaMidia(JDesktopPane parametro) {
        this();
        painelPrincipal = parametro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMidias = new javax.swing.JTable();

        setTitle("Lista de Mídias");

        tblMidias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblMidias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblMidiasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblMidias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMidiasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMidiasMousePressed
        // TODO add your handling code here:

        try {

            int indice = tblMidias.getSelectedRow();
            String id = tblMidias.getValueAt(indice, 0).toString();
            
            Midia midia = new NMidia().consultar(Integer.parseInt(id));

            CadMidia janela = new CadMidia(painelPrincipal, midia);
            painelPrincipal.add(janela);
            janela.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_tblMidiasMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMidias;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela() {
        try {

            Vector<String> cabecalho = new Vector();
            cabecalho.add("Id");
            cabecalho.add("Preço");
            cabecalho.add("Quantidade");
            cabecalho.add("Tipo da Mídia");
            cabecalho.add("Título");

            Vector detalhe = new Vector();

            for (Midia midia : new NMidia().listar()) {
                Vector<String> linha = new Vector();

                linha.add(midia.getId() + "");
                linha.add(midia.getPreco() + "");
                linha.add(midia.getQuantidade() + "");
                linha.add(midia.getTipoMidia());
                linha.add(new NTitulo().consultar(midia.getTitulo_id()).getNome());

                if (midia.isDisponibilidade() == true) {
                    linha.add("Disponível");
                } else {
                    linha.add("Indisponível");
                }

                detalhe.add(linha);

            }

            tblMidias.setModel(new DefaultTableModel(detalhe, cabecalho));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
}
