/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.Funcionario;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NFuncionario;

/**
 *
 * @author rafael
 */
public class ListaFuncionario extends javax.swing.JInternalFrame {

    JDesktopPane painelPrincipal;

    /**
     * Creates new form ListaFuncionario
     */
    public ListaFuncionario() {
        initComponents();
        carregarTabela();
    }

    public ListaFuncionario(JDesktopPane parametro) {
        this();
        painelPrincipal = parametro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();

        setTitle("Lista de Funcionários");

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblFuncionariosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblFuncionarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFuncionariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionariosMousePressed
        // TODO add your handling code here:
        
        try {

            int indice = tblFuncionarios.getSelectedRow();
            String id = tblFuncionarios.getValueAt(indice, 0).toString();

            Funcionario funcionario = new NFuncionario().consultar(Integer.parseInt(id));

            CadFuncionario janela = new CadFuncionario(painelPrincipal, funcionario);
            painelPrincipal.add(janela);
            janela.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_tblFuncionariosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFuncionarios;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela() {
        try {

            Vector<String> cabecalho = new Vector();
            cabecalho.add("Id");
            cabecalho.add("Nome");
            cabecalho.add("Cargo");

            Vector detalhe = new Vector();

            for (Funcionario funcionario : new NFuncionario().listar()) {
                Vector<String> linha = new Vector();

                linha.add(funcionario.getId() + "");
                linha.add(funcionario.getNome());
                linha.add(funcionario.getCargo());
                detalhe.add(linha);

            }

            tblFuncionarios.setModel(new DefaultTableModel(detalhe, cabecalho));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
}
