/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import entidade.Cliente;
import entidade.Titulo;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NCliente;
import negocio.NTitulo;

/**
 *
 * @author rafael
 */
public class ListaTitulo extends javax.swing.JInternalFrame {

    JDesktopPane painelPrincipal;

    /**
     * Creates new form ListaTitulo
     */
    public ListaTitulo() {
        initComponents();
        carregarTabela();
    }

    public ListaTitulo(JDesktopPane parametro) {
        this();
        painelPrincipal = parametro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTitulos = new javax.swing.JTable();

        setTitle("Lista de Títulos");
        setToolTipText("");

        tblTitulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblTitulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTitulosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblTitulos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTitulosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTitulosMousePressed
        // TODO add your handling code here:
        
        try {

            int indice = tblTitulos.getSelectedRow();
            String id = tblTitulos.getValueAt(indice, 0).toString();
            
            Titulo titulo = new NTitulo().consultar(Integer.parseInt(id));

            CadTitulo janela = new CadTitulo(painelPrincipal, titulo);
            painelPrincipal.add(janela);
            janela.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_tblTitulosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTitulos;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela() {
        try {

            Vector<String> cabecalho = new Vector();
            cabecalho.add("Id");
            cabecalho.add("Nome");
            cabecalho.add("Gênero");
            cabecalho.add("Diretor");
            cabecalho.add("Ator");
            cabecalho.add("Lançamento");
            cabecalho.add("Disponível");

            Vector detalhe = new Vector();

            for (Titulo titulo : new NTitulo().listar()) {
                Vector<String> linha = new Vector();

                linha.add(titulo.getId() + "");
                linha.add(titulo.getNome());
                linha.add(titulo.getGenero());
                linha.add(titulo.getDiretor());
                linha.add(titulo.getAtor());
                
                //formatação da data antes de jogar na view
                SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
                String result = out.format(in.parse(titulo.getDataLancamento().toString()));
                linha.add(result);
                
                if(titulo.isDisponibilidade() == true){
                    linha.add("Disponível");
                }else{
                    linha.add("Indisponível");
                }
                
                detalhe.add(linha);

            }

            tblTitulos.setModel(new DefaultTableModel(detalhe, cabecalho));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }

}
